import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { chromium } from "@playwright/test";
const MIME={".html":"text/html",".js":"text/javascript",".jsx":"text/babel",".css":"text/css",".webp":"image/webp",".jpg":"image/jpeg",".svg":"image/svg+xml",".woff2":"font/woff2"};
const dir=join(process.cwd(),"standalone_export");
const srv=createServer(async(q,s)=>{try{let p=decodeURIComponent(q.url.split("?")[0].split("#")[0]);if(p.endsWith("/"))p+="index.html";const fp=normalize(join(dir,p));const b=await readFile(fp);s.writeHead(200,{"content-type":MIME[extname(fp)]||"application/octet-stream"}).end(b);}catch{s.writeHead(404).end();}});
await new Promise(r=>srv.listen(0,"127.0.0.1",r));
const port=srv.address().port;
const t=(m)=>console.log(`[${((performance.now()-t0)/1000).toFixed(1)}s] ${m}`);
const t0=performance.now();
const b=await chromium.launch();
const p=await b.newContext({deviceScaleFactor:1,reducedMotion:"reduce"}).then(c=>c.newPage());
t("launched");
await p.goto(`http://127.0.0.1:${port}/${encodeURIComponent("Site Amore Mio v2.html")}#/`,{waitUntil:"domcontentloaded",timeout:60000});
t("goto done");
await p.evaluate(async()=>{const r=document.getElementById("root");for(let i=0;i<200&&(!r||r.childElementCount===0);i++)await new Promise(x=>setTimeout(x,100));});
t("root rendered childCount="+await p.evaluate(()=>document.getElementById("root")?.childElementCount));
await p.setViewportSize({width:1440,height:900});
t("viewport set");
const h=await p.evaluate(()=>document.body.scrollHeight); t("bodyHeight="+h);
await p.evaluate(async()=>{await document.fonts.ready;});
t("fonts ready");
const buf=await p.screenshot({fullPage:true,animations:"disabled"});
t("screenshot bytes="+buf.length);
await b.close(); srv.close();
